/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.presentacion;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import models.Aficion;
import org.itson.persistencia.AficionDAO;
import org.itson.persistencia.IAficionDAO;
import org.itson.utilidades.JPAUtil;

/**
 *
 * @author axelm
 */
public class dlgCambiarIntereses extends javax.swing.JDialog {
    private boolean crearCuenta;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgCambiarIntereses.class.getName());

    /**
     * Creates new form dlgCambiarIntereses
     */
    public dlgCambiarIntereses(java.awt.Frame parent, boolean modal, boolean crearCuenta) {
        super(parent, modal);
        this.crearCuenta = crearCuenta;
        initComponents();
        if(!crearCuenta){
            lblHobbies.setText("Seleccione el/los hobbies para filtrar");
            lblIntereses.setText("Seleccionel el/los intereses para filtrar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHobbies = new javax.swing.JLabel();
        Arte = new javax.swing.JCheckBox();
        Fotografia = new javax.swing.JCheckBox();
        Musica = new javax.swing.JCheckBox();
        Videojuegos = new javax.swing.JCheckBox();
        Baile = new javax.swing.JCheckBox();
        Coleccionismo = new javax.swing.JCheckBox();
        Jardineria = new javax.swing.JCheckBox();
        Lectura = new javax.swing.JCheckBox();
        lblIntereses = new javax.swing.JLabel();
        Deportes = new javax.swing.JCheckBox();
        Programacion = new javax.swing.JCheckBox();
        Robotica = new javax.swing.JCheckBox();
        Idiomas = new javax.swing.JCheckBox();
        CineYSeries = new javax.swing.JCheckBox();
        Moda = new javax.swing.JCheckBox();
        Turismo = new javax.swing.JCheckBox();
        Gastronomia = new javax.swing.JCheckBox();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHobbies.setText("Selecciona tus hobbies (minimo 2):");

        Arte.setText("Arte");

        Fotografia.setText("Fotografia");

        Musica.setText("Musica");

        Videojuegos.setText("Videojuegos");

        Baile.setText("Baile");

        Coleccionismo.setText("Coleccionismo");

        Jardineria.setText("Jardineria");

        Lectura.setText("Lectura");

        lblIntereses.setText("Selecciona temas de tu interes (minimo 2):");

        Deportes.setText("Deportes");

        Programacion.setText("Programacion");

        Robotica.setText("Robotica");

        Idiomas.setText("Idiomas");

        CineYSeries.setText("Cine y series");

        Moda.setText("Moda");

        Turismo.setText("Turismo");

        Gastronomia.setText("Gastronomia");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Arte)
                    .addComponent(Coleccionismo)
                    .addComponent(Videojuegos)
                    .addComponent(Baile)
                    .addComponent(Musica)
                    .addComponent(Fotografia)
                    .addComponent(Jardineria)
                    .addComponent(Lectura, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deportes)
                    .addComponent(Programacion)
                    .addComponent(Robotica)
                    .addComponent(Idiomas)
                    .addComponent(CineYSeries)
                    .addComponent(Moda)
                    .addComponent(Turismo)
                    .addComponent(Gastronomia))
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblHobbies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(lblIntereses)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(btnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHobbies)
                    .addComponent(lblIntereses))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arte)
                    .addComponent(Deportes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fotografia)
                    .addComponent(Programacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Musica)
                    .addComponent(Robotica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Videojuegos)
                    .addComponent(Idiomas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Baile)
                    .addComponent(CineYSeries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Coleccionismo)
                    .addComponent(Moda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jardineria)
                    .addComponent(Turismo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lectura)
                    .addComponent(Gastronomia))
                .addGap(42, 42, 42)
                .addComponent(btnConfirmar)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgCambiarIntereses dialog = new dlgCambiarIntereses(new javax.swing.JFrame(), true, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public Set<Aficion> obtenerAficionesSeleccionadas(boolean min){
        IAficionDAO aficionDAO = new AficionDAO();
        int minimoH = 0;
        int minimoI = 0;
        if(min){
            minimoH = 2;
            minimoI = 2;
        }
        List<String> aficionesH = new ArrayList<>();
        List<String> aficionesI = new ArrayList<>();
        Set<Aficion> aficionesSeleccionadas = new HashSet<>();
        
        if(Arte.isSelected()){
            minimoH--;
            aficionesH.add("Arte");
        }
        if(Fotografia.isSelected()){
            minimoH--;
            aficionesH.add("Fotografia");
        }
        if(Musica.isSelected()){
            minimoH--;
            aficionesH.add("Musica");
        }
        if(Videojuegos.isSelected()){
            minimoH--;
            aficionesH.add("Videojuegos");
        }
        if(Baile.isSelected()){
            minimoH--;
            aficionesH.add("Baile");
        }
        if(Coleccionismo.isSelected()){
            minimoH--;
            aficionesH.add("Coleccion");
        }
        if(Jardineria.isSelected()){
            minimoH--;
            aficionesH.add("Jardineria");
        }
        if(Lectura.isSelected()){
            minimoH--;
            aficionesH.add("Lectura");
        }
        
        if(Deportes.isSelected()){
            minimoI--;
            aficionesI.add("Deportes");
        }
        if(Programacion.isSelected()){
            minimoI--;
            aficionesI.add("Programacion");
        }
        if(Idiomas.isSelected()){
            minimoI--;
            aficionesI.add("Idiomas");
        }
        if(Robotica.isSelected()){
            minimoI--;
            aficionesI.add("Robotica");
        }
        if(CineYSeries.isSelected()){
            minimoI--;
            aficionesI.add("Cine y series");
        }
        if(Moda.isSelected()){
            minimoI--;
            aficionesI.add("Moda");
        }
        if(Turismo.isSelected()){
            minimoI--;
            aficionesI.add("Turismo");
        }
        if(Gastronomia.isSelected()){
            minimoI--;
            aficionesI.add("Gastronomia");
        }
        if(minimoI > 0){
            JOptionPane.showMessageDialog(this, "Selecciona minimo 2 temas de tu interés","Faltan intereses",JOptionPane.INFORMATION_MESSAGE);
            aficionesI.clear();
            return aficionesSeleccionadas;
        }
        if(minimoH > 0){
            JOptionPane.showMessageDialog(this, "Selecciona minimo 2 hobbies que realizas","Faltan hobbies",JOptionPane.INFORMATION_MESSAGE);
            aficionesH.clear();
            return aficionesSeleccionadas;
        }
        aficionesH.forEach(a -> {
            Aficion aficion = aficionDAO.buscarPorNombre(a, JPAUtil.getEntityManager());
            aficionesSeleccionadas.add(aficion);
        });
        aficionesI.forEach(a -> {
            Aficion aficion = aficionDAO.buscarPorNombre(a, JPAUtil.getEntityManager());
            aficionesSeleccionadas.add(aficion);
        });
        return aficionesSeleccionadas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Arte;
    private javax.swing.JCheckBox Baile;
    private javax.swing.JCheckBox CineYSeries;
    private javax.swing.JCheckBox Coleccionismo;
    private javax.swing.JCheckBox Deportes;
    private javax.swing.JCheckBox Fotografia;
    private javax.swing.JCheckBox Gastronomia;
    private javax.swing.JCheckBox Idiomas;
    private javax.swing.JCheckBox Jardineria;
    private javax.swing.JCheckBox Lectura;
    private javax.swing.JCheckBox Moda;
    private javax.swing.JCheckBox Musica;
    private javax.swing.JCheckBox Programacion;
    private javax.swing.JCheckBox Robotica;
    private javax.swing.JCheckBox Turismo;
    private javax.swing.JCheckBox Videojuegos;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblHobbies;
    private javax.swing.JLabel lblIntereses;
    // End of variables declaration//GEN-END:variables
}
