/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion;

import com.mycompany.negocios.AficionService;
import com.mycompany.negocios.IAficionService;
import java.util.HashSet;
import models.Aficion;
import models.TipoAficion;

/**
 *
 * @author HP
 */
public class frmInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmInicio.class.getName());

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        crearAficiones();
        pnlInicioSesion i = new pnlInicioSesion();
        i.setSize(elPanel.getWidth(), elPanel.getWidth());
        elPanel.removeAll();
        elPanel.add(i);
        elPanel.revalidate();
        elPanel.repaint();
        setTitle("Inicio de sesión");
    }
    
    protected void pasarACrearCuenta(){
        frmCrearCuenta registro = new frmCrearCuenta();
        registro.setVisible(true);
        this.dispose();
    }
    
    private void crearAficiones(){
        Aficion arte = new Aficion();
        arte.setNombre("Arte");
        arte.setEstudiantes(new HashSet<>());
        arte.setTipoAficion(TipoAficion.HOBBY);
        Aficion fotografia = new Aficion();
        fotografia.setNombre("Fotografia");
        fotografia.setEstudiantes(new HashSet<>());
        fotografia.setTipoAficion(TipoAficion.HOBBY);
        Aficion musica = new Aficion();
        musica.setNombre("Musica");
        musica.setEstudiantes(new HashSet<>());
        musica.setTipoAficion(TipoAficion.HOBBY);
        Aficion videojuegos = new Aficion();
        videojuegos.setNombre("Videojuegos");
        videojuegos.setEstudiantes(new HashSet<>());
        videojuegos.setTipoAficion(TipoAficion.HOBBY);
        Aficion baile = new Aficion();
        baile.setNombre("Baile");
        baile.setEstudiantes(new HashSet<>());
        baile.setTipoAficion(TipoAficion.HOBBY);
        Aficion coleccionismo = new Aficion();
        coleccionismo.setNombre("Coleccionismo");
        coleccionismo.setEstudiantes(new HashSet<>());
        coleccionismo.setTipoAficion(TipoAficion.HOBBY);
        Aficion jardineria = new Aficion();
        jardineria.setNombre("Jardineria");
        jardineria.setEstudiantes(new HashSet<>());
        jardineria.setTipoAficion(TipoAficion.HOBBY);
        Aficion lectura = new Aficion();
        lectura.setNombre("Lectura");
        lectura.setEstudiantes(new HashSet<>());
        lectura.setTipoAficion(TipoAficion.HOBBY);
        Aficion deportes = new Aficion();
        deportes.setNombre("Deportes");
        deportes.setEstudiantes(new HashSet<>());
        deportes.setTipoAficion(TipoAficion.INTERES);
        Aficion programacion = new Aficion();
        programacion.setNombre("Programacion");
        programacion.setEstudiantes(new HashSet<>());
        programacion.setTipoAficion(TipoAficion.INTERES);
        Aficion robotica = new Aficion();
        robotica.setNombre("Robotica");
        robotica.setEstudiantes(new HashSet<>());
        robotica.setTipoAficion(TipoAficion.INTERES);
        Aficion idiomas = new Aficion();
        idiomas.setNombre("Idiomas");
        idiomas.setEstudiantes(new HashSet<>());
        idiomas.setTipoAficion(TipoAficion.INTERES);
        Aficion cine = new Aficion();
        cine.setNombre("Cine y series");
        cine.setEstudiantes(new HashSet<>());
        cine.setTipoAficion(TipoAficion.INTERES);
        Aficion moda = new Aficion();
        moda.setNombre("Moda");
        moda.setEstudiantes(new HashSet<>());
        moda.setTipoAficion(TipoAficion.INTERES);
        Aficion turismo = new Aficion();
        turismo.setNombre("Turismo");
        turismo.setEstudiantes(new HashSet<>());
        turismo.setTipoAficion(TipoAficion.INTERES);
        Aficion gastronomia = new Aficion();
        gastronomia.setNombre("Gastronomia");
        gastronomia.setEstudiantes(new HashSet<>());
        gastronomia.setTipoAficion(TipoAficion.INTERES);
        IAficionService as = new AficionService();
        as.guardar(arte);
        as.guardar(fotografia);
        as.guardar(musica);
        as.guardar(videojuegos);
        as.guardar(baile);
        as.guardar(coleccionismo);
        as.guardar(jardineria);
        as.guardar(lectura);
        as.guardar(deportes);
        as.guardar(programacion);
        as.guardar(robotica);
        as.guardar(idiomas);
        as.guardar(cine);
        as.guardar(moda);
        as.guardar(turismo);
        as.guardar(gastronomia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout elPanelLayout = new javax.swing.GroupLayout(elPanel);
        elPanel.setLayout(elPanelLayout);
        elPanelLayout.setHorizontalGroup(
            elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        elPanelLayout.setVerticalGroup(
            elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(elPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel elPanel;
    // End of variables declaration//GEN-END:variables
}
