/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.presentacion;

import com.mycompany.negocios.AficionService;
import com.mycompany.negocios.EstudianteService;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import models.Aficion;
import models.Estudiante;

/**
 *
 * @author axelm
 */
public class pnlBuscarPersonas extends javax.swing.JPanel {
    private EstudianteService estudianteService;
    private AficionService aficionService;
    private Set<Aficion> filtroAficiones;

    /**
     * Creates new form pnlBuscarPersonas
     */
    public pnlBuscarPersonas() {
        initComponents();
        estudianteService = new EstudianteService();
        filtroAficiones = new HashSet<>();
        aficionService = new AficionService();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();

        lblNombre.setText("Nombre de la persona que desea buscar:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEstudiantes);

        btnBuscar.setText("Buscar por intereses");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnBuscar)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        tblEstudiantes.setModel(estudianteService.obtenerTablaEstudiantesPorFiltro(txtNombre.getText()));
    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        dlgCambiarIntereses dlg = new dlgCambiarIntereses(frame, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        filtroAficiones = dlg.obtenerAficionesSeleccionadas(false);
        if(filtroAficiones.isEmpty()){
            cargarTabla();
        }else if (filtroAficiones.size() == 1){
            Aficion[] aficionesArr = filtroAficiones.toArray(Aficion[]::new);
            List<Estudiante> estudiantes = aficionService.estAficionesSim(aficionesArr[0].getId());
            tblEstudiantes.setModel(estudianteService.obtenerTablaConLista(estudiantes));
        }else{
            Aficion[] aficionesArr = filtroAficiones.toArray(Aficion[]::new);
            List<Estudiante> estudiantesQueCoinciden = aficionService.estAficionesSim(aficionesArr[0].getId());
            for (int i = 1; i < aficionesArr.length; i++) {
                List<Estudiante> estSimilares = aficionService.estAficionesSim(aficionesArr[i].getId());
                estudiantesQueCoinciden.retainAll(estSimilares);
            }
            tblEstudiantes.setModel(estudianteService.obtenerTablaConLista(estudiantesQueCoinciden));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarTabla(){
        tblEstudiantes.setModel(estudianteService.obtenerTablaEstudiantes());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
