/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.presentacion;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Aficion;
import models.Estudiante;
import org.itson.persistencia.AficionDAO;
import org.itson.persistencia.IAficionDAO;
import org.itson.utilidades.JPAUtil;

/**
 *
 * @author HP
 */
public class pnlIntereses extends javax.swing.JPanel {
    
    Estudiante est;
    /**
     * Creates new form pnlIntereses
     */
    public pnlIntereses(Estudiante est) {
        initComponents();
        this.est = est;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HobArte = new javax.swing.JCheckBox();
        HobFotografia = new javax.swing.JCheckBox();
        HobMusica = new javax.swing.JCheckBox();
        HobVideojuegos = new javax.swing.JCheckBox();
        HobBaile = new javax.swing.JCheckBox();
        HobColeccion = new javax.swing.JCheckBox();
        HobJardineria = new javax.swing.JCheckBox();
        HobLectura = new javax.swing.JCheckBox();
        IntDeportes = new javax.swing.JCheckBox();
        IntProgramacion = new javax.swing.JCheckBox();
        IntRobotica = new javax.swing.JCheckBox();
        IntIdiomas = new javax.swing.JCheckBox();
        IntCine = new javax.swing.JCheckBox();
        IntModa = new javax.swing.JCheckBox();
        IntTurismo = new javax.swing.JCheckBox();
        IntGastronomia = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();

        HobArte.setText("Arte");

        HobFotografia.setText("Fotografia");

        HobMusica.setText("Musica");

        HobVideojuegos.setText("Videojuegos");

        HobBaile.setText("Baile");

        HobColeccion.setText("Coleccionismo");

        HobJardineria.setText("Jardineria");

        HobLectura.setText("Lectura");

        IntDeportes.setText("Deportes");

        IntProgramacion.setText("Programación");

        IntRobotica.setText("Robotica");
        IntRobotica.addActionListener(this::IntRoboticaActionPerformed);

        IntIdiomas.setText("Idiomas");
        IntIdiomas.addActionListener(this::IntIdiomasActionPerformed);

        IntCine.setText("Cine y series");
        IntCine.addActionListener(this::IntCineActionPerformed);

        IntModa.setText("Moda");
        IntModa.addActionListener(this::IntModaActionPerformed);

        IntTurismo.setText("Turismo");
        IntTurismo.addActionListener(this::IntTurismoActionPerformed);

        IntGastronomia.setText("Gastronomia");
        IntGastronomia.addActionListener(this::IntGastronomiaActionPerformed);

        jLabel1.setText("Selecciona tus hobbies (Minimo 2)");

        jLabel2.setText("Selecciona temas de tu interés (Minimo 2)");

        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.addActionListener(this::btnCrearCuentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HobLectura)
                                    .addComponent(HobJardineria)
                                    .addComponent(HobColeccion)
                                    .addComponent(HobBaile)
                                    .addComponent(HobVideojuegos)
                                    .addComponent(HobMusica)
                                    .addComponent(HobFotografia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IntProgramacion)
                                    .addComponent(IntRobotica)
                                    .addComponent(IntIdiomas)
                                    .addComponent(IntCine)
                                    .addComponent(IntModa)
                                    .addComponent(IntTurismo)
                                    .addComponent(IntGastronomia))
                                .addGap(57, 57, 57))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HobArte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(IntDeportes)
                                .addGap(82, 82, 82))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnCrearCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HobArte)
                    .addComponent(IntDeportes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HobFotografia)
                    .addComponent(IntProgramacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HobMusica)
                    .addComponent(IntRobotica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HobVideojuegos)
                    .addComponent(IntIdiomas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HobBaile)
                    .addComponent(IntCine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HobColeccion)
                    .addComponent(IntModa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IntTurismo)
                    .addComponent(HobJardineria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HobLectura)
                    .addComponent(IntGastronomia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearCuenta)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IntRoboticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntRoboticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntRoboticaActionPerformed

    private void IntIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntIdiomasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntIdiomasActionPerformed

    private void IntCineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntCineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntCineActionPerformed

    private void IntModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntModaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntModaActionPerformed

    private void IntTurismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntTurismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntTurismoActionPerformed

    private void IntGastronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntGastronomiaActionPerformed
        // yo no queria agregar ninguno de estos ayuda
    }//GEN-LAST:event_IntGastronomiaActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        obtenerAficionesSeleccionadas();
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void obtenerAficionesSeleccionadas(){
        IAficionDAO aficionDAO = new AficionDAO();
        int minimoH = 2;
        int minimoI = 2;
        List<String> aficionesH = new ArrayList<>();
        List<String> aficionesI = new ArrayList<>();
        
        if(HobArte.isSelected()){
            minimoH--;
            aficionesH.add("Arte");
        }
        if(HobFotografia.isSelected()){
            minimoH--;
            aficionesH.add("Fotografia");
        }
        if(HobMusica.isSelected()){
            minimoH--;
            aficionesH.add("Musica");
        }
        if(HobVideojuegos.isSelected()){
            minimoH--;
            aficionesH.add("Videojuegos");
        }
        if(HobBaile.isSelected()){
            minimoH--;
            aficionesH.add("Baile");
        }
        if(HobColeccion.isSelected()){
            minimoH--;
            aficionesH.add("Coleccion");
        }
        if(HobJardineria.isSelected()){
            minimoH--;
            aficionesH.add("Jardineria");
        }
        if(HobLectura.isSelected()){
            minimoH--;
            aficionesH.add("Lectura");
        }
        
        if(IntDeportes.isSelected()){
            minimoI--;
            aficionesI.add("Deportes");
        }
        if(IntProgramacion.isSelected()){
            minimoI--;
            aficionesI.add("Programacion");
        }
        if(IntIdiomas.isSelected()){
            minimoI--;
            aficionesI.add("Idiomas");
        }
        if(IntRobotica.isSelected()){
            minimoI--;
            aficionesI.add("Robotica");
        }
        if(IntCine.isSelected()){
            minimoI--;
            aficionesI.add("Cine");
        }
        if(IntModa.isSelected()){
            minimoI--;
            aficionesI.add("Moda");
        }
        if(IntTurismo.isSelected()){
            minimoI--;
            aficionesI.add("Turismo");
        }
        if(IntGastronomia.isSelected()){
            minimoI--;
            aficionesI.add("Gastronomia");
        }
        if(minimoI > 0){
            JOptionPane.showMessageDialog(this, "Selecciona minimo 2 temas de tu interés","Faltan intereses",JOptionPane.INFORMATION_MESSAGE);
            aficionesI.clear();
            return;
        }
        if(minimoH > 0){
            JOptionPane.showMessageDialog(this, "Selecciona minimo 2 hobbies que realizas","Faltan hobbies",JOptionPane.INFORMATION_MESSAGE);
            aficionesH.clear();
            return;
        }
        for (String interes : aficionesI) {
            Aficion in = aficionDAO.buscarPorNombre(interes, JPAUtil.getEntityManager());
            in.getEstudiantes().add(est);
            est.getAficiones().add(in);
        }
        for (String hobby : aficionesH) {
            Aficion hob = aficionDAO.buscarPorNombre(hobby, JPAUtil.getEntityManager());
            hob.getEstudiantes().add(est);
            est.getAficiones().add(hob);
        }
        JOptionPane.showConfirmDialog(this, "Cuenta creada con exito","Cuenta creada",JOptionPane.INFORMATION_MESSAGE);
        
        frmCrearCuenta padre = (frmCrearCuenta) SwingUtilities.getWindowAncestor(this);
        padre.volverAInicioSesion();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox HobArte;
    private javax.swing.JCheckBox HobBaile;
    private javax.swing.JCheckBox HobColeccion;
    private javax.swing.JCheckBox HobFotografia;
    private javax.swing.JCheckBox HobJardineria;
    private javax.swing.JCheckBox HobLectura;
    private javax.swing.JCheckBox HobMusica;
    private javax.swing.JCheckBox HobVideojuegos;
    private javax.swing.JCheckBox IntCine;
    private javax.swing.JCheckBox IntDeportes;
    private javax.swing.JCheckBox IntGastronomia;
    private javax.swing.JCheckBox IntIdiomas;
    private javax.swing.JCheckBox IntModa;
    private javax.swing.JCheckBox IntProgramacion;
    private javax.swing.JCheckBox IntRobotica;
    private javax.swing.JCheckBox IntTurismo;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
