/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.presentacion;

import com.mycompany.negocios.EstudianteService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Estudiante;
import org.itson.persistencia.EstudianteDAO;
import org.itson.persistencia.IEstudianteDAO;
import org.itson.utilidades.JPAUtil;
import org.itson.utilidades.RegexUtil;


/**
 *
 * @author EdgarUris
 */
public class pnlInicioSesion extends javax.swing.JPanel {
    private RegexUtil regex;
    private IEstudianteDAO estDAO;
    private EstudianteService estService;
    
    /**
     * Creates new form pnlInicioSesion
     */
    public pnlInicioSesion() {
        initComponents();
        this.regex = new RegexUtil();
        this.estDAO = new EstudianteDAO();
        this.estService = new EstudianteService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        pswContra = new javax.swing.JPasswordField();
        lblUser = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        lblNoCuenta = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnVerPass = new javax.swing.JToggleButton();

        lblBienvenido.setText("Inicio de sesion");

        txtCorreo.setColumns(15);

        pswContra.setColumns(15);

        lblUser.setText("Correo institucional:");

        lblContra.setText("Contraseña:");

        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.setBorder(null);
        btnCrearCuenta.addActionListener(this::btnCrearCuentaActionPerformed);

        lblNoCuenta.setText("¿No tienes una cuenta todavia?");

        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        btnVerPass.setText("o_o");
        btnVerPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVerPass.addActionListener(this::btnVerPassActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblContra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCorreo)
                            .addComponent(pswContra)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(lblBienvenido))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerPass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnIniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContra)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion)
                .addGap(61, 61, 61)
                .addComponent(lblNoCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String correo = txtCorreo.getText().trim();
        char[] contraChar = pswContra.getPassword();
        String contra = "";        
        for (char c : contraChar) {
            contra += c;
        }
        
        if(correo.trim().isEmpty() || contra.isEmpty()){
            JOptionPane.showMessageDialog(this, "Todos los campos son necesarios", "Campos faltantes", JOptionPane.ERROR_MESSAGE);
        }
        if(!regex.validaCorreoEstudiante(txtCorreo.getText().trim())){
            JOptionPane.showMessageDialog(this, "Usa tu correo institucional (nombre.apellidoID@potros.itson.edu.mx)", "Correo erroneo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Estudiante> ests = estDAO.buscarPorCorreo(correo, JPAUtil.getEntityManager());
        if(ests.isEmpty()){
            JOptionPane.showMessageDialog(this, "Este correo no esta registrado", "Correo no registrado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Estudiante e = ests.get(0);
        if(!e.getContrasena().equals(contra)){
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta, intenta de nuevo", 
                    "Contraseña incorrecta", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        frmVentanaPrincipal ventana = new frmVentanaPrincipal(e);
        ventana.setVisible(true);
        frmInicio padre = (frmInicio) SwingUtilities.getWindowAncestor(this);
        padre.dispose();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnVerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPassActionPerformed
        if(btnVerPass.isSelected()){
            pswContra.setEchoChar((char)0);
            btnVerPass.setText("-_-");
        }
        else{
            pswContra.setEchoChar('*');
            btnVerPass.setText("o_o");
        }
    }//GEN-LAST:event_btnVerPassActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        frmInicio padre = (frmInicio) SwingUtilities.getWindowAncestor(this);
        padre.pasarACrearCuenta();
        /*
        frmCrearCuenta registro = new frmCrearCuenta();
        registro.setVisible(true);
        */
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JToggleButton btnVerPass;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblNoCuenta;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
