/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.presentacion;

import com.mycompany.negocios.EstudianteService;
import com.mycompany.negocios.IEstudianteService;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.Estudiante;
import org.itson.utilidades.RegexUtil;

/**
 *
 * @author EdgarUris
 * @author axelm
 */
public class pnlRegistro extends javax.swing.JPanel {

    private IEstudianteService estudianteService;
    private RegexUtil regex;
    /**
     * Creates new form pnlRegistro
     */
    public pnlRegistro() {
        this.estudianteService = new EstudianteService();
        this.regex = new RegexUtil();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        pswContra = new javax.swing.JPasswordField();
        lblNombre = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        pswContraConf = new javax.swing.JPasswordField();
        lblContraConf = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        cbxCarreras = new javax.swing.JComboBox<>();
        btnVerContra = new javax.swing.JToggleButton();
        btnVerContra2 = new javax.swing.JToggleButton();
        txtSemestre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblDesc = new javax.swing.JLabel();
        btnFotoPerfil = new javax.swing.JButton();
        labelPerfil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FotoDePerfil = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        txtApellido.setColumns(15);

        pswContra.setColumns(15);
        pswContra.addActionListener(this::pswContraActionPerformed);

        lblNombre.setText("Nombre:");

        lblContra.setText("Contraseña:");

        txtCorreo.setColumns(20);

        lblCorreo.setText("Correo institucional:");

        txtNombre.setColumns(15);

        lblApellido.setText("Apellido:");

        pswContraConf.setColumns(15);
        pswContraConf.addActionListener(this::pswContraConfActionPerformed);

        lblContraConf.setText("Confirmar contraseña:");

        lblCarrera.setText("Carrera:");

        lblSemestre.setText("Semestre:");

        lblRegistro.setText("Registro de cuenta");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        cbxCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige", "Licenciatura en Administración", "Licenciatura en Administración de Empresas Turísticas", "Licenciatura en Arquitectura", "Licenciatura en Ciencias de la Educación", "Licenciatura en Ciencias del Ejercicio Físico", "Licenciatura en Contaduría Pública", "Licenciatura en Diseño Gráfico", "Licenciatura en Derecho", "Licenciatura en Economía y Finanzas", "Licenciatura en Educación Artística y Gestión Cultural", "Licenciatura en Educación Infantil", "Licenciatura en Enfermería", "Licenciatura en Psicología", "Licenciatura en Tecnología de Alimentos", "Ingeniería en Biosistemas", "Ingeniería en Biotecnología", "Ingeniería en Ciencias Ambientales", "Ingeniería Civil", "Ingeniería Electromecánica", "ngeniería en Electrónica", "Ingeniería Industrial y de Sistemas", "Ingeniería en Logística", "Ingeniería en Manufactura", "Ingeniería en Mecatrónica", "Ingeniería Química", "Ingeniería en Software ", "Medicina Veterinaria y Zootecnia", "Profesional Asociado en Desarrollo Infantil" }));

        btnVerContra.setText("o_o");
        btnVerContra.addActionListener(this::btnVerContraActionPerformed);

        btnVerContra2.setText("o_o");
        btnVerContra2.addActionListener(this::btnVerContra2ActionPerformed);

        txtSemestre.setColumns(5);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        lblDesc.setText("Descripción breve:");

        btnFotoPerfil.setText("Seleccionar imagen");
        btnFotoPerfil.addActionListener(this::btnFotoPerfilActionPerformed);

        labelPerfil.setText("Foto de perfil:");

        FotoDePerfil.setText("Aqui aparecera su foto de perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPerfil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(296, 296, 296))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(btnSiguiente)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(btnVerContra))
                                            .addComponent(lblContra, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContraConf)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pswContraConf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnVerContra2))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDesc)
                                                .addGap(64, 64, 64)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(75, 75, 75)
                                        .addComponent(FotoDePerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(122, 122, 122)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lblRegistro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblRegistro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblApellido))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContra)
                            .addComponent(lblContraConf))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerContra)
                            .addComponent(pswContraConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVerContra2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnFotoPerfil)
                                    .addComponent(btnSiguiente)))
                            .addComponent(labelPerfil)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarrera)
                        .addGap(7, 7, 7)
                        .addComponent(cbxCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesc)
                            .addComponent(lblSemestre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(FotoDePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pswContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContraActionPerformed
        //delete
    }//GEN-LAST:event_pswContraActionPerformed

    private void pswContraConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContraConfActionPerformed
        //no queria poner esto
    }//GEN-LAST:event_pswContraConfActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        boolean pasar = validarDatos();
        if(pasar){
            System.out.println("ASDAF");
            
            String nombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            String correo = txtCorreo.getText();
            char[] contraChar = pswContra.getPassword();
            String contra = "";        
            for (char c : contraChar) {
                contra += c;
            }
        
            String nombCompleto = nombre + " " + apellido;
            String carrera = cbxCarreras.getSelectedItem().toString();
            String descripcion = txtDescripcion.getText();
        
            //parte de la foto
            //Pasar imagen a arreglo de bytes
            ImageIcon fotoPerfil = (ImageIcon) FotoDePerfil.getIcon();
            Image imagen = fotoPerfil.getImage();
            BufferedImage bi = new BufferedImage(imagen.getWidth(null), imagen.getHeight(null), BufferedImage.TYPE_INT_RGB);
            Graphics2D g2 = bi.createGraphics();
            g2.drawImage(imagen, 0, 0, null);
            g2.dispose();
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try{
                ImageIO.write(bi, "jpg", baos);
            }catch(IOException ex){
                ex.printStackTrace();
            }
            byte[] fotoEnBytes = baos.toByteArray();
        
            //guardar datos
        
            Estudiante nuevoEstudiante = new Estudiante();
            nuevoEstudiante.setCarrera(carrera);
            nuevoEstudiante.setNombre(nombCompleto);
            nuevoEstudiante.setDescripcion(descripcion);
            nuevoEstudiante.setCorreo(correo);
            nuevoEstudiante.setFoto(fotoEnBytes);
            nuevoEstudiante.setContrasena(contra);
        
            //mandar datos al otro panel y reemplazar
        
            frmCrearCuenta padre = (frmCrearCuenta) SwingUtilities.getWindowAncestor(this);
            padre.pasarAIntereses(nuevoEstudiante);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private boolean validarDatos(){
        if(txtNombre.getText().trim().isEmpty() || txtApellido.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "El nombre y apellidos son obligatorios","Nombre faltante",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(!regex.validaCorreoEstudiante(txtCorreo.getText().trim())){
            JOptionPane.showMessageDialog(this, "Usa tu correo institucional (nombre.apellidoID@potros.itson.edu.mx)", "Correo erroneo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        char[] contraChar = pswContra.getPassword();
        String contra = "";        
        for (char c : contraChar) {
            contra += c;
        }
        char[] contraConfChar = pswContraConf.getPassword();
        String contraConf = "";        
        for (char c : contraConfChar) {
            contraConf += c;
        }
        
        if(!contra.equals(contraConf)){
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden","contraseñas diferentes",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try{
            int semestre = Integer.parseInt(txtSemestre.getText());
            if(semestre > 23){
                JOptionPane.showMessageDialog(this, "El semestre no puede ser 24 o mayor", "Semestre muy alto", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            if(semestre < 1){
                JOptionPane.showMessageDialog(this, "El semestre no puede ser menor a 1", "Semestre muy bajo", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "El semestre se guarda en numero entero de 1 a 23", "Semestre erroneo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(cbxCarreras.getSelectedItem() == "Elige"){
            JOptionPane.showMessageDialog(this, "Elige una carrera de las opciones", "Carrera no elegida", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if(FotoDePerfil.getIcon() == null){
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una foto de perfil", "Falta foto de perfil", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    private void btnVerContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerContraActionPerformed
        if(btnVerContra.isSelected()){
            pswContra.setEchoChar((char)0);
            btnVerContra.setText("-_-");
        }
        else{
            pswContra.setEchoChar('*');
            btnVerContra.setText("o_o");
        }
    }//GEN-LAST:event_btnVerContraActionPerformed

    private void btnVerContra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerContra2ActionPerformed
        if(btnVerContra2.isSelected()){
            pswContraConf.setEchoChar((char)0);
            btnVerContra2.setText("-_-");
        }
        else{
            pswContraConf.setEchoChar('*');
            btnVerContra2.setText("o_o");
        }
    }//GEN-LAST:event_btnVerContra2ActionPerformed

    private void btnFotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoPerfilActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filtro);
        int resultado = fileChooser.showOpenDialog(this);
        if(resultado == 0){
            File foto = fileChooser.getSelectedFile();
            ImageIcon imagen = new ImageIcon(foto.getAbsolutePath());
            Image imagenOriginal = imagen.getImage();
            Image imagenRedimensionada = imagenOriginal.getScaledInstance(FotoDePerfil.getWidth(), FotoDePerfil.getHeight(), Image.SCALE_SMOOTH);
            FotoDePerfil.setIcon(new ImageIcon(imagenRedimensionada));
            FotoDePerfil.setText("");
        }
    }//GEN-LAST:event_btnFotoPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoDePerfil;
    private javax.swing.JButton btnFotoPerfil;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JToggleButton btnVerContra;
    private javax.swing.JToggleButton btnVerContra2;
    private javax.swing.JComboBox<String> cbxCarreras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelPerfil;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblContraConf;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JPasswordField pswContraConf;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables
}
